# Generated by Django 4.2.2 on 2023-06-21 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.IntegerField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=255)),
                ('avaliacao', models.TextField()),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.aluno')),
            ],
            options={
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('professor', 'avaliacao')},
            },
        ),
    ]
